# # *****************************************************************
# #
# # Licensed Materials - Property of IBM
# #
# # (C) Copyright IBM Corp. 2018, 2019. All Rights Reserved.
# #
# # US Government Users Restricted Rights - Use, duplication or
# # disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# #
# # *****************************************************************
#
#
# All jobs defined in this file will fire when a PR is pushed.
# For now, this file should be included in the PR and only include
# the package(s) being addressed.

env:
  global:
    - secure: "NUiHEGt+lMQzO9sKAHS3snQD/PLX3yJxXnRBNB8wo8gXkupOleBy8saD4D09FvRSQAiUm/gBwzXWUxj9e/z+QUZTontmLH5/2dw1Ff6Er6BeXd1RV5/CxvjTqWfUHSVM95POmflvfKqUoFpAtzUtEYID5mHnzTRTCSJmP6amCkZjWlbOR88X8zGIYna2PM/kg/18Po73lk0nDvi2HJmJ+//SGYg1tWCTr11D2uomx9o78CGI66az0AqIiRQGgpSYh6edHyeWn/zegNMPrSFVDw57/ZPGTDu5YM/Oo4CKs24bnYqrCjLIaTVMywDaUQ9PFA7Tw7RO8d4FsmEVxw04iSniZO9bvvbQ3dRFGAEZN2Me/U8abMMrGP1DjaOeGbeD0QuW2yOu0Rsabic76tDYHKhenrCdq7Ig+o3Z3IDlehBGca+xr9rm9QxhgazOS5YWfXD2wv7J4JHVdEG1Mv2Apr0VF99UvxC0wRz/x5GJeENTSy4cexSznfdfPtMFpl+Nv6avX8SAXHelgKgceTxQTdHXEStPQzJi3lGXJbT3QyllAuy3xrJeZldA3FC+itkGmN8qd8t9tVTvYxqlDuLVGqLagrtO1ZC8MwHOcvpqxDbcNLhnXoHN0jYOz+b6qE5h9953Bqq09N9pEUFzUwQHsXsrzs3s6QlxYWPm0k6PGb0="
    - secure: "Hq8U71ydPN3+uYE4SsPt6zzf1XfSPJCABUuzsoS6DlyoJSCenl8DnhuyAate2ivD7/6lomPakWiJFo8gpSVHX7rNrVAVsREGVI530MDp8ZhWYg9HqRlG3SgdI78hAAx6fEWUEMID1hZjBz5dusWakVTqycG24o7+W13laOuYIWto8vu03mwQQ3jGm4/SabOMYswUHAm5DYNp5KAyfB7BQ99U/rAIQaCcnCzXq50ALgKAzVi7a76wU4uVh+UyLZeQtVQT40diK2TnmTFswXoKtqVc3RR4kOER0XThZ0ndstIo2k6Avz0RF3mdCv0zBo5MBz+W630fDwq6jiY1mh7MxasW82ANF7wirnwOIJNiOJIIof0bfEpGSMDgotcyzEZc+uhnidXH3vqieBj1zg2jyjnQrb39lxgMG1p6rf84PhHdi4moiy2EuQGNaQNCV9Gm6NLyPb5jOoND8Q9Ti40rLljjaEdt8kHwam48gCod5bQorg6wBbDr4p2S3bAz0n/nt4ptoNVrTLHCxUKrICPKsDGPK3/ccFqSVMGjOygrYz/PAwNhQnHOcsyP2/7p29G+QUos1hkOqti7c1fFITVaFNcJayZYyTfCEUkE3t9Q9g8/+cbBIVRKz0yTu0zSuEy/XEDw/Il0yQHAxOQwdwxrOMgxpVAWYth18rKyBeE3xLE="
    # The BINSTAR Token for uploading to anaconda.org/powerai
    - secure: "JZRf0nvjA0bNtlHCo2FiF9Xls11cYLoEK4JComWELDq0Qi1wOtlORR9t9RgyOCeldUt0n8ZiDtGVh42jCyI9xqo+lMpzZsp4GWu3apMSiDfFRNhDrakYxU1FMefathMHBCTk8rmq+P1LX7i/V+wPbNyzoSoNzcci3FmEc6eRUEGM/sBgHqH/xyvRFGZnSXbOMTigzgVSruZOVtL6opxHfo1RnxlU/dR5lytKIKm00r+GPK1w9tuwOPTdGpZUaWA6/aoxMQkUNnKqrZq382xBJ6TFgzmkkY80wJFnvchg0NuPqI7oNoA8z30W0vgYbZ7nno3SExjoCYbwCLWPlwIwsCEipEUG1lFPvVwAMELkCWu22JX95e34ZKxd5SR143/509CFMKHK5UrvLqg4tI7EgjrRpLcEI8utvNdjTCp/KUOcXbLq+cw1TMnzDwFuIdgPfsKGrTNreuaiHxCdt2NKuy8oD497WcMOUpq4rWoWXjDXeUfwxOt6GEH1F07Em5Ng0mSiwyCHxiL5XERpYj4lAnSnMBIaIXaHOWlGpron0jAtcpTu3lIY2rF7zdpUFSGNVnaiwwHUD7RDxy96zc/ig0X7DVIofeNTTML/rYsHEbB+hO92sBll+lxEq1xjeAO8Khsp0ohJLOyM3iglBgHxXrSfLhcYk6pmKrOqi1onJK0="


jobs:
  include:

    # tensorflow-hub recipe CONDA_PY=36
    - stage: tensorflow-hub
      language: generic

      os: linux-ppc64le

      env: CONDA_PY= CONFIG=linux_noarch UPLOAD_PACKAGES=True

      script:
          -  cd conda-recipes/tensorflow-hub-feedstock # cd to pygdf dir
          -  ./ci_support/run_docker_build.sh tensorflow-hub-0.5-py
